version: "3"
services:
  calculator-service:
    build: ./calculator-service
    ports:
      - "8888:8888"
    depends_on:
      - kafka
      - mongo_db


  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mongo_db
      - redis


  proposal-service:
    build: ./list-of-proposal-service
    ports:
      - "9000:9000"
    depends_on:
      - kafka


  redis:
    image: redis:latest
    container_name: redis-latest
    restart: unless-stopped
    expose:
      - 6379

  mongo_db:
    container_name: mongo-db-latest
    image: mongo:latest
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
